packages:
  - root
  - apps/*
  - libs/*
  - config/*
  - tools/*

catalogMode: prefer

catalogs:
  commit-hooks:
    '@changesets/cli': ^2.29.8
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    '@commitlint/cz-commitlint': ^20.1.0
    commitizen: ^4.3.1
    husky: ^9.1.7
    lint-staged: ^16.2.7
  default:
    copyfiles: 2.4.1
    dotenv-cli: ^11.0.0
    npm-run-all2: ^8.0.4
    rimraf: ^6.1.2
    turbo: ^2.6.1
  eslint:
    '@eslint/compat': ^1.4.1
    '@eslint/eslintrc': ^3.3.3
    '@eslint/js': ^9.39.1
    '@next/eslint-plugin-next': ^16.0.7
    '@types/eslint-plugin-security': ^3.0.0
    '@typescript-eslint/utils': ^8.48.1
    eslint: ^9.39.1
    eslint-config-next: 16.0.1
    eslint-config-prettier: ^10.1.8
    eslint-plugin-import: ^2.32.0
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    eslint-plugin-security: ^3.0.1
    eslint-plugin-turbo: ^2.6.1
    globals: ^16.5.0
    markdownlint: ^0.39.0
    markdownlint-cli: ^0.45.0
    typescript-eslint: ^8.48.1
  hookform:
    '@hookform/error-message': ^2.0.1
    '@hookform/resolvers': ^5.2.2
    react-hook-form: ^7.67.0
  i18n:
    next-intl: ^4.5.8
    use-intl: ^4.5.8
  next:
    '@next/third-parties': ^16.0.7
    next: 16.0.2
    sharp: ^0.34.5
  node:
    '@types/node': ^22.19.1
  nodemailer:
    '@types/nodemailer': ^7.0.4
    nodemailer: ^7.0.11
  prettier:
    prettier: ^3.7.4
    prettier-plugin-packagejson: ^2.5.20
    prettier-plugin-tailwindcss: ^0.7.2
  react:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: ^19.2.1
    react-dom: ^19.2.1
  react-email:
    '@react-email/components': ^0.5.7
    '@react-email/render': ^1.4.0
    react-email: 4.2.8
  tailwind:
    '@tailwindcss/postcss': ^4.1.17
    tailwindcss: ^4.1.17
  tanstack:
    '@tanstack/react-form': ^1.19.2
  typescript:
    typescript: ^5.9.3
  ui-kit:
    '@headlessui/react': ^2.2.9
    '@phosphor-icons/react': ^2.1.10
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    embla-carousel: ^8.6.0
    embla-carousel-react: ^8.6.0
    framer-motion: ^12.23.25
    react-hot-toast: ^2.6.0
    react-player: ^3.4.0
    tailwind-merge: ^3.3.1
  zod:
    zod: ^4.1.13
    zod-form-data: ^3.0.1
